// src/components/list/ListItem.tsx
import React, { useState, useRef, useCallback } from 'react';
import { useStore } from '@/store/store';
import Card from '@/typings/card';
import CardCreateInput from '@/components/card/CardCreateInput';
import CardItem from '@/components/card/CardItem';
import ListOptions from '@/components/list/ListOptions';
import ListType from '@/typings/list';
import Plus from '@/assets/icons/plus.svg';
import LoadingIcon from '@/assets/icons/loadingIcon.svg';
import { Droppable, Draggable } from '@hello-pangea/dnd';
import { useClickOutside } from '@/hooks/useClickOutside';

interface ListItemProps {
  list: ListType;
  index: number;
}

const ListItem: React.FC<ListItemProps> = ({ list }) => {
  const [cardCreate, setCardCreate] = useState(false);
  const patchList = useStore((s) => s.patchList);
  const loadingListCards = useStore((s) => s.loadingListCards);
  const wrapperRef = useRef<HTMLInputElement>(null);

  const onClickAway = useCallback(() => {}, []);
  useClickOutside(wrapperRef, onClickAway);

  const showCardCreate = (flag: boolean) => {
    setCardCreate(flag);
  };

  return (
    <div className="relative p-1.5 mb-32 ml-3 w-list bg-gray2 rounded shadow-md" data-test-id="list">
      <div className="flex mb-1">
        <input
          ref={wrapperRef}
          className="inline-block flex-grow py-0.5 px-1 h-8 text-sm font-semibold text-gray-900 bg-gray2 focus:bg-gray1 rounded-sm border-2 border-transparent focus:border-blue6 outline-none cursor-pointer"
          data-test-id="list-name"
          defaultValue={list.name}
          onMouseUp={(e) => {
            (e.target as HTMLInputElement).select();
          }}
          onChange={(e) => {
            patchList(list, { name: e.target.value });
          }}
          onKeyUp={(e) => {
            if (e.key === 'Enter') {
              (e.target as HTMLInputElement).blur();
            }
          }}
        />
        <ListOptions list={list} onToggleInput={showCardCreate} />
      </div>
      <div data-test-id="card-list">
        {loadingListCards[list.id] && (
          <div className="block place-self-center text-xs text-center">
            <LoadingIcon className="inline-block mb-1" />
            &nbsp;&nbsp;Loading cards ...
          </div>
        )}
        <Droppable droppableId={String(list.id)} type="card">
          {(provided) => (
            <div ref={provided.innerRef} {...provided.droppableProps} className="min-h-[2px]">
              {list.cards?.map((card: Card, cardIndex: number) => (
                <Draggable key={card.id} draggableId={String(card.id)} index={cardIndex}>
                  {(provided) => (
                    <div ref={provided.innerRef} {...provided.draggableProps} {...provided.dragHandleProps}>
                      <CardItem card={card} />
                    </div>
                  )}
                </Draggable>
              ))}
              {provided.placeholder}
            </div>
          )}
        </Droppable>
        {!cardCreate ? (
          <div
            className="py-1.5 px-2 text-sm font-normal text-gray-500 hover:text-gray-600 hover:bg-gray4 rounded-md cursor-pointer"
            data-test-id="new-card"
            onClick={() => showCardCreate(true)}
          >
            <Plus className="inline-block w-3 h-3" />
            Add another card
          </div>
        ) : (
          <CardCreateInput list={list} onToggleInput={showCardCreate} />
        )}
      </div>
    </div>
  );
};

export default ListItem;

// src/components/list/ListItem.vue
<template>
  <div
    class="relative p-1.5 mb-32 ml-3 w-list bg-gray2 rounded shadow-md"
    data-cy="list"
    @dragenter="isDragging = true"
    @dragleave="isDragging = false"
  >
    <div class="flex mb-1">
      <input
        v-click-away="onClickAway"
        class="inline-block py-0.5 px-1 h-8 text-sm font-semibold text-gray-900 bg-gray2 focus:bg-gray1 rounded-sm border-2 border-transparent focus:border-blue6 outline-none cursor-pointer flex-grow"
        data-cy="list-name"
        :value="list.name"
        @mouseup="
          selectInput($event);
          inputActive = true;
        "
        @change="patchList(list, { name: inputValue($event) })"
        @keyup.enter="
          blurInput($event);
          inputActive = false;
        "
        @blur="inputActive = false"
      >
      <Dropdown
        :list="list"
        @toggle-input="showCardCreate"
      />
    </div>
    <div
      data-cy="card-list"
      :class="isDragging ?? 'min-h-[100px]'"
    >
      <div
        v-if="loadingListCards[list.id]"
        class="block place-self-center text-xs text-center"
      >
        <LoadingIcon class="inline-block mb-1" />&nbsp;&nbsp;Loading cards ...
      </div>
      <draggable
        :list="list.cards"
        animation="150"
        group="cards"
        ghost-class="bg-gray2"
        :item-key="list.name"
        @change="sortCards"
      >
        <template #item="{ element }">
          <CardItem :card="element" />
        </template>
      </draggable>
      <div
        v-if="!cardCreate"
        class="py-1.5 px-2 text-sm font-normal text-gray-500 hover:text-gray-600 hover:bg-gray4 rounded-md cursor-pointer"
        data-cy="new-card"
        @click="showCardCreate(true)"
      >
        <Plus class="inline-block w-3 h-3" />Add another card
      </div>
      <CardCreateInput
        v-else
        :list="list"
        @toggle-input="showCardCreate"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { PropType, ref } from 'vue';
import { blurInput } from '@/utils/blurInput';
import { inputValue } from '@/utils/inputValue';
import { selectInput } from '@/utils/selectInput';
import { store } from '@/stores/store';
import Card from '@/typings/card';
import CardCreateInput from '@/components/card/CardCreateInput.vue';
import CardItem from '@/components/card/CardItem.vue';
import Dropdown from '@/components/list/Dropdown.vue';
import List from '@/typings/list';
import Plus from '@/assets/icons/plus.svg';
import draggable from 'vuedraggable';
import LoadingIcon from '@/assets/icons/loadingIcon.svg';
import { storeToRefs } from 'pinia';

const props = defineProps({
  list: {
    default: null,
    type: Object as PropType<List>,
  },
});

const cardCreate = ref(false);
const inputActive = ref(false);
const isDragging = ref(false);

const { lists, loadingListCards } = storeToRefs(store());
const { patchCard, patchList } = store();

const onClickAway = () => {
  inputActive.value = false;
};
const showCardCreate = (flag: boolean) => {
  cardCreate.value = flag;
};
const sortCards = () => {
  const listIndex = lists.value.findIndex((l: List) => l.id === props.list.id);
  lists.value[listIndex].cards.forEach((card: Card, order: number) => {
    patchCard(card, { listId: props.list.id, order });
  });
};
</script>
