// src/components/board/BoardItem.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Board from '@/typings/board';
import Star from '@/assets/icons/star.svg';
import { useStore } from '@/store/store';

interface BoardItemProps {
  board: Board;
}

const BoardItem: React.FC<BoardItemProps> = ({ board }) => {
  const patchBoard = useStore((s) => s.patchBoard);
  const navigate = useNavigate();
  const [showStar, setShowStar] = useState(false);

  return (
    <div
      className="grid grid-cols-6 justify-between py-3 px-4 w-72 h-36 bg-blue7 hover:bg-blue8 rounded-sm cursor-pointer"
      id={`board-${board.id}`}
      data-test-id="board-item"
      onClick={() => navigate(`/board/${board.id}`)}
      onMouseOver={() => setShowStar(true)}
      onMouseOut={() => setShowStar(false)}
    >
      <h2 className="col-span-5 font-bold text-white">{board.name}</h2>
      {showStar && (
        <div
          data-test-id="star"
          className="justify-self-end self-start"
          onClick={(e) => {
            e.stopPropagation();
            patchBoard(board, { starred: !board.starred });
          }}
        >
          <Star className={`col-span-1 w-5 h-5 ${board.starred ? 'fill-current text-yellow-300' : 'stroke-current text-white'}`} />
        </div>
      )}
    </div>
  );
};

export default BoardItem;

// src/components/board/BoardItem.vue
<template>
  <router-link
    v-slot="{ navigate }"
    custom
    :to="{ path: '/board/' + board.id }"
  >
    <div
      :id="'board-' + board.id"
      class="board"
      data-cy="board-item"
      @click="navigate"
      @mouseover="showStar = true"
      @mouseout="showStar = false"
    >
      <h2>
        {{ board.name }}
      </h2>
      <div
        v-show="showStar"
        data-cy="star"
        class="star"
        @click.stop="patchBoard(board, { starred: !board.starred })"
      >
        <Star
          class="col-span-1 w-5 h-5"
          :class="[board.starred ? 'fill-current text-yellow-300' : 'stroke-current text-white']"
        />
      </div>
    </div>
  </router-link>
</template>

<script setup lang="ts">
import { PropType, ref } from 'vue';
import Board from '@/typings/board';
import Star from '@/assets/icons/star.svg';
import { useStore } from '@/store/store';

const { patchBoard } = useStore();
defineProps({
  board: {
    default: null,
    type: Object as PropType<Board>,
  },
});

let showStar = ref(false);
</script>

<style lang="postcss" scoped>
.board {
  @apply bg-blue7 w-72 h-36 px-4 py-3 cursor-pointer grid grid-cols-6 justify-between rounded-sm hover:bg-blue8;
}
.star {
  @apply justify-self-end self-start;
}
h2 {
  @apply text-white font-bold col-span-5;
}
</style>
