// src/components/boardList/BoardList.tsx
import React, { useEffect } from 'react';
import { useStore } from '@/store/store';
import BoardCreate from '@/components/board/BoardCreate';
import BoardItem from '@/components/board/BoardItem';
import Emptylist from '@/components/boardList/Emptylist';
import LoadingError from '@/components/boardList/LoadingError';
import Loading from '@/components/Loading';

const BoardList: React.FC = () => {
  const state = useStore();
  const starred = state.starred();
  const allBoards = state.allBoards();

  useEffect(() => {
    state.getBoardList();
  }, []);

  return (
    <div className="grid h-screen bg-white background" style={{ height: 'calc(100vh - 40px)' }} data-test-id="board-list">
      <Loading />
      {state.loadingError.show && <LoadingError />}
      {!state.loading && !state.loadingError.show && (
        <div className="container mx-auto">
          {starred.length > 0 && (
            <div>
              <h1 className="inline-block py-5 mx-4 text-3xl font-semibold" data-test-id="starred-boards">
                Starred
              </h1>
              <div className="flex flex-wrap flex-grow gap-8 content-start mx-4 flex-cols-3">
                {starred.map((board) => (
                  <BoardItem key={board.id} board={board} />
                ))}
                {!allBoards.length && <BoardCreate />}
              </div>
            </div>
          )}
          {allBoards.length > 0 && (
            <div>
              <h1 className="inline-block py-5 mx-4 text-3xl font-semibold">My Boards</h1>
              <div className="flex flex-wrap flex-grow gap-8 content-start mx-4 flex-cols-3">
                {allBoards.map((board) => (
                  <BoardItem key={board.id} board={board} />
                ))}
                <BoardCreate />
              </div>
            </div>
          )}
        </div>
      )}
      {!state.loading && !state.boardList.all.length && !state.loadingError.show && <Emptylist />}
    </div>
  );
};

export default BoardList;

// src/components/board/BoardList.vue
<template>
  <div class="background bg-white h-screen grid" data-cy="board-list">
    <div class="loading place-self-center" v-if="state.loading">
      <Loading class="inline-block"/>&nbsp;&nbsp;Loading data ...
    </div>

    <div v-cloak class="container mx-auto" v-else>
      <!-- STARRED BOARDS -->
      <h1
        class="text-3xl py-5 font-semibold inline-block"
        v-show="state.starred.length"
      >
        Starred
      </h1>
      <div class="flex flex-cols-3 gap-8 flex-wrap">
        <BoardItem
          v-for="board in state.starred"
          :key="board.id"
          :board="board"
        />
      </div>

      <!-- ALL BOARDS -->
      <h1 class="text-3xl py-5 font-semibold inline-block">My Boards</h1>
      <div class="flex flex-cols-3 gap-8 flex-wrap">
        <BoardItem v-for="board in state.boardList.all" :key="board.id" :board="board" />
        <BoardCreate></BoardCreate>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { store } from '@/stores/store';
import { defineComponent } from 'vue';
import BoardItem from '@/components/board/BoardItem.vue';
import BoardCreate from '@/components/board/BoardCreate.vue';
import Loading from '@/assets/icons/loading.svg';
export default defineComponent({
  setup() {
    const state = store();
    state.getBoardList();
    return { state };
  },
  name: 'BoardList',
  components: {
    BoardItem,
    BoardCreate,
    Loading
  }
});
</script>

<style lang="postcss" scoped></style>
