// src/views/Board.vue
<template>
  <div class="h-screen bg-blue6">
    <CardDetail v-if="cardModule" />
    <BoardDetail />
  </div>
</template>

<script setup lang="ts">
import { useStore } from '@/stores/store';
import BoardDetail from '@/components/board/BoardDetail.vue';
import CardDetail from '@/components/card/CardDetail.vue';
import { storeToRefs } from 'pinia';

const { cardModule } = storeToRefs(useStore());
</script>

// src/views/Board.tsx
import React from 'react';
import { useStore } from '@/store/store';
import BoardDetail from '@/components/board/BoardDetail';
import CardDetail from '@/components/card/CardDetail';

const Board: React.FC = () => {
  const cardModule = useStore((s) => s.cardModule);

  return (
    <div className="bg-blue6">
      {cardModule && <CardDetail />}
      <BoardDetail />
    </div>
  );
};

export default Board;
