// src/components/NotFound.tsx
import React from 'react';
import { Link } from 'react-router-dom';

const NotFound: React.FC = () => {
  return (
    <div>
      <div className="grid h-screen bg-white background">
        <div className="place-self-center" data-test-id="404">
          <span className="block mb-4 text-8xl font-bold text-center text-gray-200">404</span>
          <p className="block mb-4 text-center text-gray-400">Sorry, this board does not exist</p>
          <Link to="/" className="block font-semibold text-center text-blue7">
            Go back home
          </Link>
        </div>
      </div>
    </div>
  );
};

export default NotFound;

// src/views/NotFound.vue
<template>
  <div>
    <div class="background bg-white h-screen grid">
      <div
        class="place-self-center"
        data-cy="404"
      >
        <span class="font-bold text-8xl text-gray-200 text-center block mb-4">404</span>
        <p class="text-gray-400 text-center block mb-4">
          Sorry, this board does not exist
        </p>
        <router-link
          to="/"
          class="text-blue7 font-semibold text-center block"
        >
          Go back home
        </router-link>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  name: 'Board'
};
</script>
