// src/components/Checkbox.tsx
import React from 'react';
import { useStore } from '@/store/store';
import Card from '@/typings/card';

interface CheckboxProps {
  card: Card;
}

const Checkbox: React.FC<CheckboxProps> = ({ card }) => {
  const patchCard = useStore((s) => s.patchCard);

  return (
    <label className="inline-flex items-center">
      <input
        type="checkbox"
        data-test-id="card-checkbox"
        checked={card.completed}
        className="w-4 h-4 text-blue5 outline-none"
        onClick={(e) => {
          e.stopPropagation();
          patchCard(card, { completed: !card.completed });
        }}
        readOnly
      />
    </label>
  );
};

export default Checkbox;

// src/components/Checkbox.vue
<template>
  <label class="inline-flex items-center">
    <input
      class="text-blue5 w-4 h-4 outline-none"
      type="checkbox"
      data-cy="card-checkbox"
      :checked="card.completed"
      @click.stop="patchCard(card, { completed: !card.completed })"
    >
  </label>
</template>

<script lang="ts">
import { PropType, defineComponent } from 'vue';
import { store } from '@/stores/store';
import Card from '@/typings/card';
export default defineComponent({
  props: {
    card: {
      default: null,
      type: Object as PropType<Card>
    }
  },
  setup() {
    const patchCard = store().patchCard;
    return { patchCard };
  }
});
</script>
