// src/components/Loading.vue
<template>
  <div
    v-if="loading"
    class="loading"
  >
    <LoadingIcon class="inline-block mb-1" />&nbsp;&nbsp;Loading data ...
    <div
      v-if="loadingError.tooLong"
      class="block mt-4"
    >
      This is taking too long.
      <a href="/"> Reload? </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import LoadingIcon from '@/assets/icons/loadingIcon.svg';
import { useStore } from '@/stores/store';
import { storeToRefs } from 'pinia';
const { loading, loadingError } = storeToRefs(useStore());
</script>

<style lang="postcss" scoped>
.loading {
  @apply place-self-center text-center block;
}

a {
  @apply text-blue7 font-semibold text-center;
}
</style>

// src/components/Loading.tsx
import React from 'react';
import LoadingIcon from '@/assets/icons/loadingIcon.svg';
import { useStore } from '@/store/store';

const Loading: React.FC = () => {
  const loading = useStore((s) => s.loading);
  const loadingError = useStore((s) => s.loadingError);

  if (!loading) return null;

  return (
    <div className="block place-self-center text-center">
      <LoadingIcon className="inline-block mb-1" />
      &nbsp;&nbsp;Loading data ...
      {loadingError.tooLong && (
        <div className="block mt-4">
          This is taking too long.
          <a href="/" className="font-semibold text-center text-blue7">
            {' '}
            Reload?{' '}
          </a>
        </div>
      )}
    </div>
  );
};

export default Loading;
