// src/components/list/Dropdown.vue
<template>
  <Dots @click="showDropdown()" />
  <div
    v-if="dropdown"
    class="bg-white absolute rounded-sm top-11 shadow-xl z-10 w-dropdown left-dropdown right-8 py-2"
    v-click-away="onClickAway"
  >
    <div class="text-gray-600 text-sm h-7 mt-0.5 text-center">List actions</div>
    <Cross
      class="w-8 h-8 px-2 text-gray-600 absolute top-1 right-1 cursor-pointer"
      @click="dropdown = false"
    />
    <hr />
    <div class="pt-2">
      <div
        class="text-gray-700 text-sm py-1 block cursor-pointer hover:bg-gray1 px-2 active:bg-gray2"
        @click="
          this.$emit('toggleInput', true);
          dropdown = false;
        "
      >
        Add card...
      </div>
      <div
        class="text-red-600 text-sm py-1 block cursor-pointer hover:bg-gray1 px-2 active:bg-gray2"
        @click="deleteList(list.id); showDropdown()"
      >
        Delete this list
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { boardDetail } from "@/stores/boardDetail";
import Cross from '@/assets/icons/cross.svg';
import Dots from '@/assets/icons/dots.svg';
export default defineComponent({
  setup() {
    const deleteList = boardDetail().deleteList;
    return { deleteList };
  },
  data() {
    return {
      dropdown: false,
      id: this.list.id
    };
  },
  components: {
    Dots,
    Cross
  },
  emits: ['toggleInput'],
  props: ['list'],
  methods: {
    showDropdown() {
      this.dropdown = !this.dropdown;
    },
    onClickAway() {
      this.dropdown = false;
    }
  }
});
</script>

<style></style>

// src/components/common/Dropdown.tsx
import React, { useRef } from 'react';
import Cross from '@/assets/icons/cross.svg';
import { useClickOutside } from '@/hooks/useClickOutside';

interface DropdownProps {
  header?: string;
  onClose: () => void;
  children?: React.ReactNode;
  'data-test-id'?: string;
}

const Dropdown: React.FC<DropdownProps> = ({ header, onClose, children, 'data-test-id': dataTestId }) => {
  const ref = useRef<HTMLDivElement>(null);
  useClickOutside(ref, onClose);

  return (
    <div ref={ref} data-test-id={dataTestId} className="absolute top-11 left-2 z-10 py-2 w-dropdown bg-white rounded-sm shadow-xl">
      <div className="mt-0.5 h-7 text-sm text-center text-gray-600">{header}</div>
      <Cross data-test-id="cancel" className="absolute top-1 right-1 px-2 w-8 h-8 text-gray-600 cursor-pointer" onClick={onClose} />
      <hr />
      {children}
    </div>
  );
};

export default Dropdown;
